cf

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -1,22 +1,31 @@
-# This buildspec file is for the CI/CD pipeline of the serverless backend.
-# It packages the Lambda function and the CloudFormation template.
 version: 0.2
 
+# The `buildspec.yml` is the instruction manual for the CodeBuild worker.
 phases:
-  pre_build:
+  install:
     commands:
-      # Install the AWS Serverless Application Model (SAM) CLI
-      - echo Installing SAM CLI...
-      - pip install aws-sam-cli
+      # This command ensures we have the AWS Serverless Application Model (SAM)
+      # command-line tool available in the build environment.
+      - |
+        if ! command -v sam &> /dev/null
+        then
+            echo "SAM CLI not found. Installing..."
+            pip install aws-sam-cli
+        else
+            echo "SAM CLI is already installed."
+        fi
 
   build:
     commands:
-      # The sam package command zips up your Lambda function and uploads it to S3.
-      # It then returns a new template file that contains the S3 location of your code artifact.
-      - echo Packaging the serverless application...
-      - sam package --template-file project-tracker-backend.yaml --s3-bucket project-tracker-be-artifacts --output-template-file packaged.yaml
+      - echo "Starting the SAM package build..."
+      # CRITICAL: The `sam package` command is what prepares your code for deployment.
+      # It zips the contents of the `CodeUri` folder (`./src/`), uploads it to the
+      # S3 bucket, and then creates a new CloudFormation template (`packaged.yaml`)
+      # that references the new location of the code in S3.
+      - sam package --template-file project-tracker-backend.yaml --s3-bucket $LambdaCodeBucketName --output-template-file packaged.yaml
 
+# The `artifacts` section tells the pipeline which files to send to the next stage.
+# We are now sending the `packaged.yaml` file, not the source files.
 artifacts:
   files:
-    # We will upload the packaged.yaml file to our S3 bucket, which can then be used by CloudFormation.
     - packaged.yaml
